# Generated by Django 4.1.13 on 2025-05-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cara_pembuatan',
            field=models.TextField(default='Belum ada cara pembuatan.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(choices=[('plastik', 'Plastik'), ('kaca', 'Kaca'), ('logam', 'Logam'), ('elektronik', 'Elektronik'), ('mainan', 'Mainan'), ('kain', 'Kain'), ('karet', 'Karet'), ('kertas', 'Kertas')], default='plastik', max_length=20),
            preserve_default=False,
        ),
    ]
