# Generated by Django 4.2.7 on 2025-12-15 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0002_comment_delete_explorecomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='product',
        ),
    ]
