# Generated by Django 4.1.13 on 2025-05-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('category', models.CharField(choices=[('organik', 'Organik'), ('anorganik', 'Anorganik')], max_length=20)),
                ('materials', models.TextField()),
                ('product_type', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('mudah', 'Mudah (<1 hari)'), ('standar', 'Standar (1 hari)'), ('sulit', 'Sulit (>1 hari)')], max_length=20)),
            ],
        ),
    ]
