# Generated by Django 4.2.7 on 2025-06-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0005_rename_text_comment_content_remove_comment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(upload_to='product_media/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(max_length=50),
        ),
    ]
