# Generated by Django 4.2.7 on 2025-05-25 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('file_path', models.FileField(upload_to='content_files/')),
                ('caption', models.TextField(blank=True, null=True)),
                ('materials', models.TextField(blank=True, null=True)),
                ('duration_label', models.CharField(choices=[('<=1hari', '≤ 1 hari'), ('1hari', '1 hari'), ('>=1hari', '≥ 1 hari')], max_length=10)),
                ('category', models.CharField(choices=[('Organik', 'Organik'), ('Anorganik', 'Anorganik')], max_length=10)),
                ('hashtags', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('waste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.waste')),
            ],
            options={
                'db_table': 'create_content',
            },
        ),
    ]
