# Generated by Django 4.2.7 on 2025-12-15 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('create', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='products/')),
                ('category', models.CharField(choices=[('Organik', 'Organik'), ('Anorganik', 'Anorganik')], max_length=50)),
                ('subcategory', models.CharField(choices=[('Plastik', 'Plastik'), ('Kertas', 'Kertas'), ('Logam', 'Logam'), ('Kaca', 'Kaca'), ('Kain', 'Kain'), ('Karet', 'Karet'), ('Elektronik', 'Elektronik'), ('Styrofoam', 'Styrofoam'), ('Mainan', 'Mainan'), ('Daun', 'Daun'), ('Sisa Makanan', 'Sisa Makanan'), ('Kulit Buah', 'Kulit Buah'), ('Sayur Busuk', 'Sayur Busuk'), ('Sekam Padi', 'Sekam Padi'), ('Ranting Kayu', 'Ranting Kayu'), ('Ampas Teh', 'Ampas Teh'), ('Ampas Kopi', 'Ampas Kopi'), ('Kulit Telur', 'Kulit Telur'), ('Kertas Tisu', 'Kertas Tisu'), ('Tulang Ikan', 'Tulang Ikan'), ('Bunga Layu', 'Bunga Layu')], max_length=50)),
                ('materials', models.TextField()),
                ('product_type', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=20)),
                ('cara_pembuatan', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CreateContent',
        ),
    ]
